name: action

on:
  push:
    branches: [ master ]
    tags: - 'release*'
  pull_request:
    branches: [ master ]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew compileJava
  Test:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Archive test folder to artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_file
          path: build/reports/tests/test/*
  Assemble:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - name: Archive Jar file to artifact
        uses: actions/upload-artifact@v2
        with:
          name: jarfile
          path: build/libs/*.jar
  Release:
    runs-on: ubuntu-latest
    needs: Assemble
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: jarfile
          files: build/libs/*.jar



