name: action

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew compileJava
      - name: Display structure of downloaded files
        run: ls -R
  Test:
    runs-on: ubuntu-latest
    needs: Compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew test
      - name: Archive test folder to artifact
        uses: actions/upload-artifact@v2
        with:
          name: test_file
          path: build/reports/tests/test/*
  Assemble:
    runs-on: ubuntu-latest
    needs: [Compile, Test]
    outputs:
      output1: ${{ steps.step1.outputs.filepath }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble with Gradle
        run: ./gradlew assemble
      - id: step1
        run: echo "::set-output name=filepath::./build/libs/*.jar"
      - name: Archive Jar file to artifact
        uses: actions/upload-artifact@v2
        with:
          name: jarfile
          path: ./build/libs/*.jar
  Release:
    runs-on: ubuntu-latest
    needs: [Compile, Test, Assemble]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
      - name: Download jar files
        uses: actions/download-artifact@v2
        with:
          name: jarfile
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






